name: Bug Report
description: 버그를 신고합니다
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        버그 리포트를 작성해 주셔서 감사합니다.

  - type: textarea
    id: description
    attributes:
      label: 버그 설명
      description: 무엇이 문제인가요?
      placeholder: 버그에 대해 설명해주세요
    validations:
      required: true

  - type: textarea
    id: reproduce
    attributes:
      label: 재현 방법
      description: 버그를 재현하는 단계
      placeholder: |
        1. '...'로 이동
        2. '...'를 클릭
        3. 에러 발생
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: 예상 동작
      description: 어떻게 동작해야 하나요?
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: 실제 동작
      description: 실제로 어떻게 동작하나요?
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: 환경
      description: OS, 브라우저, 버전 등
      placeholder: |
        - OS: macOS 14
        - Node: 20.x
        - Browser: Chrome 120

  - type: textarea
    id: logs
    attributes:
      label: 로그/스크린샷
      description: 관련 로그나 스크린샷이 있다면 첨부해주세요

  - type: textarea
    id: ai-context
    attributes:
      label: AI Context
      description: AI가 이 이슈를 찾고 이해하는 데 필요한 정보
      placeholder: |
        keywords: Dream Security, 드림시큐리티, mobileOK, ACCOUNT_006
        files: src/auth/mobileok.ts
        deps: mok-key-manager
        related: #12, #34
