name: Task (일반 작업)
description: 일반 작업을 등록합니다
title: "[Task]: "
labels: ["task"]
body:
  - type: textarea
    id: description
    attributes:
      label: 작업 내용
      description: 무엇을 해야 하나요?
    validations:
      required: true

  - type: textarea
    id: checklist
    attributes:
      label: 체크리스트
      description: 완료 조건
      placeholder: |
        - [ ] 항목 1
        - [ ] 항목 2

  - type: textarea
    id: notes
    attributes:
      label: 참고 사항
