name: Task (일반 작업)
description: 일반 작업을 등록합니다
title: "[Task]: "
labels: ["task"]
body:
  - type: textarea
    id: description
    attributes:
      label: 작업 내용
      description: 무엇을 해야 하나요?
    validations:
      required: true

  - type: textarea
    id: checklist
    attributes:
      label: 체크리스트
      description: 완료 조건
      placeholder: |
        - [ ] 항목 1
        - [ ] 항목 2

  - type: textarea
    id: notes
    attributes:
      label: 참고 사항

  - type: textarea
    id: ai-context
    attributes:
      label: AI Context
      description: AI가 이 이슈를 찾고 이해하는 데 필요한 정보
      placeholder: |
        keywords: 영문명, 한글명, 변수명, 에러코드
        files: src/auth/example.ts
        deps: library-name
        related: #이슈번호
