name: Topic (주제/토론)
description: 자유 형식으로 주제를 등록합니다
title: "[Topic]: "
labels: ["topic"]
body:
  - type: textarea
    id: description
    attributes:
      label: 내용
      description: 자유롭게 작성해주세요
    validations:
      required: true

  - type: textarea
    id: ai-context
    attributes:
      label: AI Context
      description: AI가 이 이슈를 찾고 이해하는 데 필요한 정보
      placeholder: |
        keywords: Dream Security, 드림시큐리티, mobileOK, ACCOUNT_006
        files: src/auth/mobileok.ts
        deps: mok-key-manager
        related: #12, #34
